// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LMMS.Core.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LMMS.Core
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> InitializeLeaveBalanceAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
