// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LMMS.Core.Entities;

public partial class EmployeeLeaveBalance
{
    public int EmployeeLeaveBalanceId { get; set; }

    public int Id { get; set; }

    public int LeaveTypeId { get; set; }

    public int AvailableDays { get; set; }

    public virtual User IdNavigation { get; set; }

    public virtual LeaveType LeaveType { get; set; }
}